version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db-hp
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hpbackend
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: